os: osx

language: cpp

addons:
  homebrew:
    packages:
    - llvm
    - cmake
    - ninja
    update: true

before_script:
  - LDFLAGS='-L/usr/local/opt/llvm/lib -W1,-rpath,/usr/local/opt/llvm/lib'
  - CPPFLAGS='-I/usr/local/opt/llvm/include'
  - C_INCLUDE_PATH='/usr/local/opt/llvm/include'
  - CC='/usr/local/opt/llvm/bin/clang'
  - CXX='/usr/local/opt/llvm/bin/clang++'
  - CXX_COMPILER='/usr/local/opt/llvm/bin/clang++'
  - C_COMPILER='/usr/local/opt/llvm/bin/clang'
  - BUILD_TYPE='Release'

script:
# Build IWYU
# comment
  - mkdir build
  - cd build
  - cmake -GNinja -DCMAKE_PREFIX_PATH=/usr/local/opt/llvm/ ..
  - ninja install
  - cd ..
  - python run_iwyu_tests.py -- build/bin/include-what-you-use
  - python fix_includes_test.py
  - python iwyu_tool_test.py
