os: osx

language: cpp

addons:
  homebrew:
    packages:
    - llvm
    - cmake
    - ninja

env:
  - LDFLAGS='-L/usr/local/opt/llvm/lib -W1,-rpath,/usr/local/opt/llvm/lib'
  - CPPFLAGS='-I/usr/local/opt/llvm/include'
  - C_INCLUDE_PATH='/usr/local/opt/llvm/include'
  - CC='/usr/local/opt/llvm/bin/clang'
  - CXX='/usr/local/opt/llvm/bin/clang++'
  - CXX_COMPILER='/usr/local/opt/llvm/bin/clang++'
  - C_COMPILER='/usr/local/opt/llvm/bin/clang'
  - BUILD_TYPE='Release'

before_install:
  - echo "before_install says hi"

before_script:
  - echo "before_script says hi"

script:
# Build IWYU
# comment
  - mkdir build
  - cd build
  - cmake -GNinja -DCMAKE_PREFIX_PATH=/usr/local/opt/llvm/ ..
  - ninja install
# Test IWYU
 - cd ..
 - python run_iwyu_tests.py -- build/bin/include-what-you-use
 - python fix_includes_test.py
 - python iwyu_tool_test.py
